name: Deploy Worker
on:
  push:
    branches:
      - main

concurrency:
  group: deploy-worker
  cancel-in-progress: true

jobs:
  check:
    uses: ./.github/workflows/pull.yaml
    name: Check code quality
  deploy:
    name: Deploy to Cloudflare Workers
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: check
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
      - uses: oven-sh/setup-bun@v2
        name: Setup Bun
        with:
            bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Build project
        run: bun run build
        env:
            NODE_OPTIONS: "--max_old_space_size=4096"
      - name: Publish to Cloudflare Workers
        run: bun wrangler deploy .output/server/index.mjs --assets .output/public
        env:
            CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      