on:
  pull_request:
    branches: [main]
  workflow_call:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        name: Checkout repository
      - uses: oven-sh/setup-bun@v2
        name: Setup Bun
        with:
            bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Lint and Format
        run: |
          bun run biome ci .
      - name: Typecheck
        run: bun run tsc --noEmit
        
      